project:
  type: website

website:
  title: Evan Lum
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    background: "#3F352E"

editor: visual

execute:
  freeze: auto 
