project:
  type: website

website:
  title: Evan Lum
    navbar:
    left:
      - href: index.qmd
        text: test
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

